[package]
name = "graphql_server"
version = "0.1.0"
authors = ["w <pylint@yandex.com>"]
edition = "2018"


[dependencies]
actix-web = "3.0.0"
async-graphql = "2.0.0-alpha.7"
async-graphql-actix-web = "2.0.0-alpha.7"
#slab = "0.4.2"
serde_json = "*"